project_id = "rtcilpxtgvbarxvewaqh"

[functions.enrich-repo]
verify_jwt = false

[functions.run-enrichment]
verify_jwt = false

[functions.search-repos]
verify_jwt = false

[functions.build-longlist]
verify_jwt = false
